void BurnupChain::AddPseudoFPD5(int fissile_num, int *matid_fp, real *yield_fp, real *dc)
{
   for(int i=0;i<fissile_num-1;i++){
    int id=matid_fp[i]-99000000;
    if(data[id].GetID()!=0){
      data[id].AddFissionYield(matid_fp[i], yield_fp[i]);
      data[matid_fp[i]].PutID(matid_fp[i]);
      data[matid_fp[i]].PutNdiv(0,1,1,1); // f,c,2n,d
      data[matid_fp[i]].PutData(1,1.,matid_fp[i]); // The same nuclide is generated by capture reaction. 
      data[matid_fp[i]].PutData(2,1.,matid_fp[i]); // The same nuclide is generated by (n,2n) reaction.
      data[matid_fp[i]].PutData(3,1.,matid_fp[i+1]); // Another pseudo FP is generated by decay.
      PutDecayConstant(matid_fp[i], dc[i]);
    };
   };
   int id=matid_fp[4]-99000000;
    if(data[id].GetID()!=0){
      data[id].AddFissionYield(matid_fp[4], yield_fp[4]);
      data[matid_fp[4]].PutID(matid_fp[4]);
      data[matid_fp[4]].PutNdiv(0,1,1,1); // f,c,2n,d
      data[matid_fp[4]].PutData(1,1.,matid_fp[4]); // The same nuclide is generated by capture reaction. 
      data[matid_fp[4]].PutData(2,1.,matid_fp[4]); // The same nuclide is generated by (n,2n) reaction.
      data[matid_fp[4]].PutData(3,1.,matid_fp[4]); // Another pseudo FP is generated by decay.
    };
};
